### ISSUE TITLE
Support for active failover

### ISSUE THREAD

**Issue by EliyaCohen** [arangodb/python-arango#160]
Hey,
It would be nice to see support for interacting with active failover arangodb deployments.

Currently, when querying active failover deployments there is no way to determine which of the servers is the leader.

I suggest adding the functionality to automatically determine who the leader and in case the current leader fails, move on to the next leader.

**Comment by joowani** [comment]
Hi @EliyaCohen,

I'll add this in the todo list for next release.

**Comment by EliyaCohen** [comment]
Thanks a lot! if you have implementation ideas I'd love to contribute the code.

**Comment by bryaninbi** [comment]
Is this issue still open / is there still no support for active-failover? I have implemented support that is deployed in a production scenario currently that I would happily contribute if there is interest, but it's probably terrible code. It does work, it's not elegant, and I was just getting back into python after a ten year hiatus.

**Comment by joowani** [comment]
Hi @bryaninbi,

Please feel free to share your code. Even if it's not polished it might help get me started. Thanks.

**Comment by joowani** [comment]
Discussions on how to implement active failover: https://github.com/arangodb/arangodb/issues/13860

**Comment by franciszac-dlc** [comment]
Hey, is this issue still in the roadmap for implementation? We ran across this roadbump and we plan on working around it for our own use case, however I might be willing to contribute in my free time once I have more time in my hands

**Comment by apetenchea** [comment]
Hello! While this issue is indeed on our radar, it's not in our immediate roadmap. However, contributions are always welcome, if you can find the time and inclination to do so. Thanks for reaching out and for considering contributing!

**Comment by aMahanna** [comment]
Closing this issue as Active Failover has been deprecated in favour of using [cluster deployments](https://docs.arangodb.com/stable/deploy/cluster/): https://docs.arangodb.com/stable/release-notes/deprecated-and-removed-features/
